const express = require('express');
const router = express.Router();
const vtuConsoleController = require('../controllers/vtuConsoleController');
const { protect, requireTransactionPin } = require('../middlewares/auth');
const { adminAuth } = require('../middlewares/admin');

router.get('/providers', adminAuth, vtuConsoleController.getAllProviders);
router.post('/providers', adminAuth, vtuConsoleController.createProvider);
router.get('/providers/markups', adminAuth, vtuConsoleController.getProviderMarkups);
router.get('/providers/markups/options', adminAuth, vtuConsoleController.getProviderMarkupOptions);
router.put('/providers/:providerId/markups', adminAuth, vtuConsoleController.setProviderMarkup);
router.get('/providers/profiles', adminAuth, vtuConsoleController.getProviderProfiles);
router.get('/providers/config', vtuConsoleController.getProviderConfig);
router.get('/config', adminAuth, vtuConsoleController.getServiceConfig);
router.post('/config', adminAuth, vtuConsoleController.saveServiceConfig);
router.get('/providers/:providerId', adminAuth, vtuConsoleController.getProvider);
router.put('/providers/:providerId', adminAuth, vtuConsoleController.updateProvider);
router.delete('/providers/:providerId', adminAuth, vtuConsoleController.deleteProvider);
router.get('/providers/:providerId/stats', adminAuth, vtuConsoleController.getProviderStats);
router.get('/providers/:providerId/balance', adminAuth, vtuConsoleController.getProviderBalance);
router.post('/switch', adminAuth, vtuConsoleController.switchProvider);
router.post('/health', adminAuth, vtuConsoleController.runHealthCheck);
router.post('/providers/:providerId/health', adminAuth, vtuConsoleController.runProviderHealthCheck);
router.get('/balances', adminAuth, vtuConsoleController.getProviderBalances);
router.get('/logs', adminAuth, vtuConsoleController.getApiLogs);
router.put('/providers/:providerId/status', adminAuth, vtuConsoleController.updateProviderStatus);
router.post('/init', adminAuth, vtuConsoleController.initializeProviders);
router.get('/bill-payment/providers', adminAuth, vtuConsoleController.getBillPaymentProviders);
router.post('/bill-payment/switch', adminAuth, vtuConsoleController.switchBillPaymentProvider);

module.exports = router;
